# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59b8de362ccca3c0e9f183dbb52dcc0eee4ef4b704bed532d19347ffa1ff983237b1f47edeadc6582b17399b4deddb597beda1ceb7ecf3e769e4a4fa171c384e

test:
  secret_key_base: 3ff3d740321220c603b9b23f8df810f394b250d23def8ec844491d31fe6e653d72a2ad2a39e3fa572cb428d1c3967c4e80068a331386a7b97f76a9429ce8524a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
